kind = "web"
previewPath = "/"
title = "Dabis Studio"
version = "1.0.0"
id = "artifacts/dabisstudio"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19803

[services.development]
run = "pnpm --filter @workspace/dabisstudio run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/dabisstudio", "run", "build" ]
publicDir = "artifacts/dabisstudio/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19803"
BASE_PATH = "/"
